# Generated by Django 4.0.6 on 2023-07-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
